### ISSUE TITLE
Do not use mtime comparision to determine file task execution

### ISSUE THREAD

**Issue by srackham** [srackham/drake#4]
Timestamp-only file task dependency checking is fraught with problems, see [mtime comparison
considered harmful](https://apenwarr.ca/log/20181113).

This is further complicated by the fact that `Deno.utime` and `Deno.utimeSync` APIs have been marked
"unstable" in Deno 1.0.0-rc1 and they have [resolution limitations](https://github.com/denoland/deno/issues/5065).

Drake's file task dependency check mechanism should not rely on target and prerequisite file
timestamp comparisions.

**Comment by srackham** [comment]
Resolved with the introduction of file history caching in Drake v1.0.0-rc2.

**Comment by duncanmak** [comment]
@srackham I'm using Drake 1.5.2 and I noticed that on Windows, the mtime check in `isOutOfDate` is returning `true` all the time.

```
isOutOfDate: build\index.html: true: build\index.html
from: {"size":532,"mtime":"2022-06-07T21:29:05.186Z"}
to:   {"size":532,"mtime":"2022-06-07T23:21:29.811Z"}
```

I was scanning the same article you referred to, [mtime comparison considered harmful](https://apenwarr.ca/log/20181113), and I wonder if a better check could be implemented instead of checking that the result of `Date.toISOString` is `!==`.

An interesting note, I only see this error when running in Windows - on Linux (in WSL, no less), `isOutOfDate` returns `false` as expected after running the same target a second time.

**Comment by srackham** [comment]
Thanks for this, very interesting. I'll look into it when I get some free time.

**Comment by srackham** [comment]
@duncanmak The only possibilities I can think of are that somehow the Drake cache file is not being updated after a sucessful task execution (if the task action is executed sucessfully then the Drake cache should be updated) or the information returned by the `Deno.statSync` API is stale.

Try cloning the Drake repo and running the Drake tests on WSL with `deno run -A Drakefile.ts test` command (I don't have WSL installed).
